---
title: "Data_cleaning"
author: "Ziqin Zhao"
date: "2/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(tidyverse)
library(ggmap)
library(choroplethr)
library(revgeo)
```


```{r}
data<-read_csv("crimeNYC2019.csv")
crime_mahattan<-data%>%
  rename(Date=ARREST_DATE,Area=ARREST_BORO,Crime_type=OFNS_DESC)%>%
  drop_na()%>%
  filter(Area=="M",str_detect(Crime_type,c("ASSAULT","WEAPONS","ROBBERY","MURDER","RAPE",
                                                     "KIDNAPPING","PETIT LARCENY","GRAND LARCENY",
                                           "DRUGS","SEX")))%>% 
  
  select(Date,Crime_type,Longitude,Latitude)%>%
  mutate(Crime_type=str_replace_all(Crime_type,"RAPE","SEX CRIMES"),
         Crime_type=str_replace_all(Crime_type,"PETIT LARCENY","LARCENY"),
         Crime_type=str_replace_all(Crime_type,"GRAND LARCENY","LARCENY"),
         Crime_type=str_replace_all(Crime_type,"GRAND LARCENY OF MOTOR VEHICLE","LARCENY"),
         Crime_type=str_replace_all(Crime_type,"LARCENY OF MOTOR VEHICLE","LARCENY"),
         Crime_type=str_replace_all(Crime_type,"ASSAULT 3 & RELATED OFFENSES","ASSAULT"),
         Crime_type=str_replace_all(Crime_type,"FELONY ASSAULT","ASSAULT"),
         Crime_type=str_replace_all(Crime_type,"MURDER & NON-NEGL. MANSLAUGHTE","MURDER"),
         Crime_type=str_replace_all(Crime_type,"KIDNAPPING & RELATED OFFENSES","KIDNAPPING"))



#save(crime_mahattan, file="crime_mahattan.Rdata")

load("crime-mahattan-geo-info.RData")
crime_mahattan_geo_info<-crime_mahattan_geo_info%>%
  filter(zip!="83",
         zip!="Postcode Not Found",
         zip!="100",
         zip!="100014")%>%
  mutate(zip=str_replace_all(zip,"NY ",""),
         zip=substr(zip,1,5))

save(crime_mahattan_geo_info, file="crime_mahattan.Rdata")
load("crime_mahattan.Rdata")
crime_mahattan_geo_info




```

```{r}
library(geosphere)
distHaversine(c(-73.9705912,40.7930732), c(-73.9679734,40.7928133), r=6378137)
load("../output/housing.RData")

hou<-housing%>%
  mutate(house_id=row_number())%>%
  rename("house_Longitude"="Longitude","house_Latitude"="Latitude")
cri<-crime_mahattan_geo_info%>%
  mutate(crime_id=row_number())%>%
  rename("crime_Longitude"="Longitude","crime_Latitude"="Latitude")


hla=hou$house_Latitude
hlo=hou$house_Longitude
n=length(hla)

cla=cri$crime_Latitude
clo=cri$crime_Longitude
m<-length(cla)


index<-NULL
for(i in 1:5){
  crime_amount=0
  for(j in 1:5){
    dist<-distHaversine(c(hlo[i],hla[i]),c(clo[j],cla[j]),r=6378137)
    if(!is.na(dist))if(dist<800)  crime_amount<-crime_amount+1
  }
  index<-rbind(index,tibble(house_id=i,crime_amount=crime_amount))
}

index
dataset<-index%>%left_join(cri)%>%
  group_by(crime_id)%>%
  nest(crime_data=-house_id)%>%
  right_join(hou)








```


```{r}
load("restaurant.RData")
restaurant<-newdata%>%filter(BORO=="Manhattan",
                             GRADE %in% c("A","B","C"))%>%
  rename(TYPE=CUISINE.DESCRIPTION)%>%
  select(DBA,ZIPCODE,TYPE,GRADE,Latitude,Longitude)
restaurant
```


```{r}
load("park_NYC_new.RData")
park_new
```

```{r}

restaurant_manhattan_new<-restaurant_unique_manhattan%>%
  filter(BORO=="Manhattan")%>%
  filter(GRADE %in% c("A","B","C"))%>%
  select(DBA,ZIPCODE,GRADE,Latitude,Longitude)

restaurant_manhattan_new

save(restaurant_manhattan_new,file="../output/restaurant_manhattan_new.RData")
```


```{r}
housing<-hous%>%na.omit()
```

